# Generated by Django 4.1.2 on 2022-11-01 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usermodel_is_subscribed'),
        ('commitment', '0009_causeofcategorysuccessorfailuremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonBehindCommitmentSuccessOrFailureForUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cause_of_category_success_or_failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commitment.causeofcategorysuccessorfailuremodel')),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
